version: '3'
services:
  db:
    image: mysql:8
    container_name: restaurant_db
    restart: always
    volumes:
      - data:/var/lib/mysql
    env_file:
      - ./Backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate --noinput && python manage.py makemessages -l fa && python manage.py compilemessages && gunicorn API.wsgi --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  data: