version: '3'
services:
  db:
    image: mysql:8
    container_name: restaurant_db
    restart: always
    volumes:
      - data:/var/lib/mysql
    env_file:
      - ./Backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
  
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    command: sh -c "python3 manage.py migrate --noinput && python manage.py collectstatic && python manage.py makemessages -l fa && python manage.py compilemessages && gunicorn --bind 0.0.0.0:8000 API.wsgi"
    restart: always
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile  
    container_name: nginx
    restart: always
    ports:
      - "80:80"  
    depends_on:
      - backend  

volumes:
  data: