version: '3'
services:
  db:
    image: mysql:8
    container_name: restaurant_db
    restart: always
    volumes:
      - data:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: django

    command: sh -c "gunicorn API.wsgi --bind 0.0.0.0:8000"
    restart: always
    volumes:
      -  media_volume:/vol/media
      - ./Backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - media_volume:/vol/media
    ports:
      - "80:80"
      - "8001:8001"
    depends_on:
      - backend

volumes:
  data:
  media_volume: