export default [
  { id: 1, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 2, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 3, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 4, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 5, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 6, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 7, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 8, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 9, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 10, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 11, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 12, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 13, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 14, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 15, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 16, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 17, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 18, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 19, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 20, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 21, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 22, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 23, name: "", category: "", caption: "", price: 10, image: "" },
  { id: 24, name: "", category: "", caption: "", price: 10, image: "" },
];
