# Generated by Django 5.0.2 on 2024-02-12 15:04

import autoslug.fields
import common.utils.custom_slug_utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=355, verbose_name='نام')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', slugify=common.utils.custom_slug_utils.custom_slugify, unique=True, verbose_name='کد شماره صفحه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='عکس')),
            ],
            options={
                'verbose_name_plural': 'طبقه بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='title', slugify=common.utils.custom_slug_utils.custom_slugify, unique=True, verbose_name='کد شماره صفحه')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='عکس')),
                ('available', models.CharField(choices=[('YES', 'موجود'), ('', 'عدم موجودی')], default='YES', max_length=3, verbose_name='وضعیت موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='app.category', verbose_name='طبقه بندی')),
            ],
            options={
                'verbose_name_plural': 'آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='ItemFoodValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام')),
                ('value', models.PositiveIntegerField(verbose_name='ارزش')),
                ('unit', models.CharField(default='گرم', max_length=30, verbose_name='واحد')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_food_values', to='app.item')),
            ],
            options={
                'verbose_name_plural': 'ارزش های غذایی',
            },
        ),
        migrations.CreateModel(
            name='ItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام')),
                ('weight', models.PositiveIntegerField(verbose_name='وزن')),
                ('unit', models.CharField(default='گرم', max_length=30, verbose_name='واحد')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ingredients', to='app.item')),
            ],
            options={
                'verbose_name_plural': 'مواد غذایی',
            },
        ),
    ]
