# Generated by Django 5.0.1 on 2024-02-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Ingredients',
            new_name='ingredients',
        ),
    ]
