# Generated by Django 5.0.1 on 2024-02-04 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='app.category'),
        ),
        migrations.AlterField(
            model_name='itemfoodvalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_food_values', to='app.item'),
        ),
        migrations.AlterField(
            model_name='itemingredient',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ingredients', to='app.item'),
        ),
    ]
